/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardOnboardingRouteImport } from './routes/dashboard.onboarding'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardQrRouteImport } from './routes/dashboard.qr'
import { Route as DashboardScannerRouteImport } from './routes/dashboard.scanner'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardShareRouteImport } from './routes/dashboard.share'
import { Route as DashboardOnboardingIndexRouteImport } from './routes/dashboard.onboarding.index'
import { Route as DashboardOnboardingFillRouteImport } from './routes/dashboard.onboarding.fill'
import { Route as DashboardSoonSlugRouteImport } from './routes/dashboard.soon.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQrRoute = DashboardQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScannerRoute = DashboardScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShareRoute = DashboardShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingIndexRoute =
  DashboardOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOnboardingRoute,
  } as any)
const DashboardOnboardingFillRoute = DashboardOnboardingFillRouteImport.update({
  id: '/fill',
  path: '/fill',
  getParentRoute: () => DashboardOnboardingRoute,
} as any)
const DashboardSoonSlugRoute = DashboardSoonSlugRouteImport.update({
  id: '/soon/$slug',
  path: '/soon/$slug',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/scanner': typeof DashboardScannerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/onboarding/fill': typeof DashboardOnboardingFillRoute
  '/dashboard/soon/$slug': typeof DashboardSoonSlugRoute
  '/dashboard/onboarding/': typeof DashboardOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/scanner': typeof DashboardScannerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/onboarding/fill': typeof DashboardOnboardingFillRoute
  '/dashboard/soon/$slug': typeof DashboardSoonSlugRoute
  '/dashboard/onboarding': typeof DashboardOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/scanner': typeof DashboardScannerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/onboarding/fill': typeof DashboardOnboardingFillRoute
  '/dashboard/soon/$slug': typeof DashboardSoonSlugRoute
  '/dashboard/onboarding/': typeof DashboardOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/dashboard/documents'
    | '/dashboard/notifications'
    | '/dashboard/onboarding'
    | '/dashboard/profile'
    | '/dashboard/qr'
    | '/dashboard/scanner'
    | '/dashboard/settings'
    | '/dashboard/share'
    | '/dashboard/'
    | '/dashboard/onboarding/fill'
    | '/dashboard/soon/$slug'
    | '/dashboard/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/dashboard/documents'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/qr'
    | '/dashboard/scanner'
    | '/dashboard/settings'
    | '/dashboard/share'
    | '/dashboard'
    | '/dashboard/onboarding/fill'
    | '/dashboard/soon/$slug'
    | '/dashboard/onboarding'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/dashboard/documents'
    | '/dashboard/notifications'
    | '/dashboard/onboarding'
    | '/dashboard/profile'
    | '/dashboard/qr'
    | '/dashboard/scanner'
    | '/dashboard/settings'
    | '/dashboard/share'
    | '/dashboard/'
    | '/dashboard/onboarding/fill'
    | '/dashboard/soon/$slug'
    | '/dashboard/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/onboarding': {
      id: '/dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/qr': {
      id: '/dashboard/qr'
      path: '/qr'
      fullPath: '/dashboard/qr'
      preLoaderRoute: typeof DashboardQrRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scanner': {
      id: '/dashboard/scanner'
      path: '/scanner'
      fullPath: '/dashboard/scanner'
      preLoaderRoute: typeof DashboardScannerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/share': {
      id: '/dashboard/share'
      path: '/share'
      fullPath: '/dashboard/share'
      preLoaderRoute: typeof DashboardShareRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/onboarding/': {
      id: '/dashboard/onboarding/'
      path: '/'
      fullPath: '/dashboard/onboarding/'
      preLoaderRoute: typeof DashboardOnboardingIndexRouteImport
      parentRoute: typeof DashboardOnboardingRoute
    }
    '/dashboard/onboarding/fill': {
      id: '/dashboard/onboarding/fill'
      path: '/fill'
      fullPath: '/dashboard/onboarding/fill'
      preLoaderRoute: typeof DashboardOnboardingFillRouteImport
      parentRoute: typeof DashboardOnboardingRoute
    }
    '/dashboard/soon/$slug': {
      id: '/dashboard/soon/$slug'
      path: '/soon/$slug'
      fullPath: '/dashboard/soon/$slug'
      preLoaderRoute: typeof DashboardSoonSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardOnboardingRouteChildren {
  DashboardOnboardingFillRoute: typeof DashboardOnboardingFillRoute
  DashboardOnboardingIndexRoute: typeof DashboardOnboardingIndexRoute
}

const DashboardOnboardingRouteChildren: DashboardOnboardingRouteChildren = {
  DashboardOnboardingFillRoute: DashboardOnboardingFillRoute,
  DashboardOnboardingIndexRoute: DashboardOnboardingIndexRoute,
}

const DashboardOnboardingRouteWithChildren =
  DashboardOnboardingRoute._addFileChildren(DashboardOnboardingRouteChildren)

interface DashboardRouteChildren {
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOnboardingRoute: typeof DashboardOnboardingRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQrRoute: typeof DashboardQrRoute
  DashboardScannerRoute: typeof DashboardScannerRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardShareRoute: typeof DashboardShareRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSoonSlugRoute: typeof DashboardSoonSlugRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOnboardingRoute: DashboardOnboardingRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQrRoute: DashboardQrRoute,
  DashboardScannerRoute: DashboardScannerRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardShareRoute: DashboardShareRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSoonSlugRoute: DashboardSoonSlugRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
